repos:
- repo: https://github.com/psf/black
  rev: 21.6b0
  hooks:
  - id: black

- repo: https://github.com/PyCQA/isort
  rev: 5.9.1
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    exclude: ^tests/
    additional_dependencies:
    - types-cryptography
