name: Test PSRPCore
on:
  push:
    branches:
    - main
    paths-ignore:
    - CHANGELOG.md
    - LICENSE
    - README.md

  pull_request:
    branches:
    - main
    paths-ignore:
    - CHANGELOG.md
    - LICENSE
    - README.md

  release:
    types:
    - published

jobs:
  docs:
   name: docs
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v3

    - name: Install
      run: |
        echo "Installing baseline pip packages"

        python -m pip install -U pip setuptools

        python -m pip install -e .
        python -m pip install -r requirements-docs.txt

    - name: Build docs
      run: |
        cd docs
        make html-strict

  build:
    name: build project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install build pre-requisites
      run: python -m pip install build

    - name: build sdist and wheel
      run: python -m build --sdist --wheel

    - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ./dist/*

  test:
    name: test
    needs:
    - build

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        python-version:
        - 3.7
        - 3.8
        - 3.9
        - '3.10'
        - '3.11'
        python-arch:
        - x86
        - x64

        exclude:
        - os: ubuntu-latest
          python-arch: x86

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}

    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ./dist

    - name: Extract OS name
      shell: bash
      run: |
        echo NAME=$( echo '${{ matrix.os }}' | tr '-' ' ' | awk '{print $1}' )
        echo "name=${NAME}" >> $GITHUB_OUTPUT
      id: os

    - name: Install
      shell: bash
      run: |
        python -m pip install build

        echo "Installing psrpcore"
        if [ "$(expr substr $(uname -s) 1 5)" == "MINGW" ]; then
            DIST_LINK_PATH="$( echo "${PWD}/dist" | sed -e 's/^\///' -e 's/\//\\/g' -e 's/^./\0:/' )"
        else
            DIST_LINK_PATH="${PWD}/dist"
        fi

        PSRPCORE_VERSION="$( python -c "import build.util; print(build.util.project_wheel_metadata('.').get('Version'))" )"

        python -m pip install psrpcore=="${PSRPCORE_VERSION}" \
            --find-links "file://${DIST_LINK_PATH}" \
            --verbose

        echo "Installing dev dependencies"
        python -m pip install -r requirements-dev.txt

    - name: Run Sanity Test
      shell: bash
      run: |
        python -m black . --check
        python -m isort . --check-only

        # mypy has false positives on these older versions
        PY_VER="$( python -c "import sys; ver = sys.version_info; print(f'cp{ver.major}{ver.minor}')" )"
        if [ "${PY_VER}" != "cp37" ]; then
            python -m mypy .
        fi

    - name: Run Tests
      run: |
        python -m pytest -v --junitxml junit/test-results.xml --cov psrpcore --cov-report xml --cov-report term-missing

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Unit Test Results (${{ matrix.os }} ${{ matrix.python-version }} ${{ matrix.python-arch }})
        path: ./junit/test-results.xml

    - name: Upload Coverage Results
      if: always() && !startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v3
      with:
        name: Coverage Results (${{ matrix.os }} ${{ matrix.python-version }} ${{ matrix.python-arch }})
        path: ./coverage.xml

    - name: Upload Coverage to codecov
      if: always()
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: ${{ steps.os.outputs.name }},py${{ matrix.python-version }},${{ matrix.python-arch }}

  publish:
    name: publish
    needs:
    - docs
    - test
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ./dist

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
